apiVersion: v1
kind: Service
metadata:
  name: hello-world-ml-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-world-ml
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000